name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23litOpBCMx0QGi5pM"
GITHUB_OWNER = "borisCai"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://hainan0898.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://hainan0898.dpdns.org/"

